KVM: guest_mem: hugetlb: allocate and truncate from hugetlb
Introduce kvm_gmem_hugetlb_get_folio(), then update
kvm_gmem_allocate() and kvm_gmem_truncate() to use hugetlb functions.

Backport change:
- Adjust some some function the input paramter from "file"-> "inode"
- Add the file parameter "file" to kvm_gmem_hugetlb_setup(struct inode *inode,
       struct file *file, struct kvm_gmem *gmem,loff_t size, u64 flags)
- Delete the rcu_read_lock()/unlock() between filemap_lock_folio(mapping, hindex)
- Init the gmem flags
- Fix the build error, when the CONFIG_KVM=m CONFIG_KVM_INTEL=m
ERROR: modpost: "size_to_hstate" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "default_hstate_idx" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "restore_reserve_on_error" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "hugetlb_filemap_add_folio" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "hugepage_new_subpool" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "resv_map_alloc" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "vma_dummy_vm_ops" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "alloc_hugetlb_folio_from_subpool" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "hugetlb_fault_mutex_hash" [arch/x86/kvm/kvm.ko] undefined!
ERROR: modpost: "hstates" [arch/x86/kvm/kvm.ko] undefined!

Signed-off-by: Ackerley Tng <ackerleytng@google.com>
[ Jun Miao: amend commit log ]
Signed-off-by: Jun Miao <jun.miao@intel.com>